project_0:
  url: "/"
  description: "Environment set up"
project_1:
  url: "/"
  description: "Custom home page route"
project_2:
  url: "/pages/project_2"
  description: "Description of Bootstrap set up"
project_3/4:
  url: "/calendar"
  description: "A basic interactive calendar"